### ISSUE TITLE
Problem with LTI Store plugin in Tutor Open edX

### ISSUE THREAD

**Issue by mkalisch** [open-craft/openedx-ltistore#3]
Hi, 

Could you explain how to properly install and configure this plugin in tutor version of open edx? I installed it adding plugin source code into "$(tutor config printroot)/env/build/openedx/requirements/" directory, adding plugin directory path into "private.txt" file and building tutor images (tutor images build openedx). I migrated the database. I added "OPEN_EDX_FILTERS_CONFIG" using yml plugin:

```
name: lti-store-config
version: 0.1.0
patches:
    lms-env: |
      OPEN_EDX_FILTERS_CONFIG:
        org.openedx.xblock.lti_consumer.configuration.listed.v1:
          fail_silently: false
          pipeline:
            - lti_store.pipelines.GetLtiConfigurations
    cms-env: |
      OPEN_EDX_FILTERS_CONFIG:
        org.openedx.xblock.lti_consumer.configuration.listed.v1:
          fail_silently: false
          pipeline:
            - lti_store.pipelines.GetLtiConfigurations
```

I can see and use the "LTI Store" configuration in the admin panel. But I still cannot find the "External ID" field on the LTI consumer XBlock editor in studio.

Do you have any idea what else I can do, or maybe I misunderstood something?
